//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int Flight_Number { get; set; }
        public string Flight_Status { get; set; }
        public Nullable<System.TimeSpan> Flight_Departure_Time { get; set; }
        public Nullable<System.TimeSpan> Flight_Arrival_Time { get; set; }
        public Nullable<int> Passenger_Id { get; set; }
        public Nullable<int> Airplane_Id { get; set; }
    
        public virtual Airplane Airplane { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
