//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int Staff_Id { get; set; }
        public string Staff_Position { get; set; }
        public string Staff_Name { get; set; }
        public Nullable<long> Staff_Phone_Number { get; set; }
        public string Staff_Username { get; set; }
        public string Staff_Password { get; set; }
        public string Staff_Nickname { get; set; }
    }
}
